/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIRecipeImport: typeof import('./src/components/features/AIRecipeImport.vue')['default']
    AppNavbar: typeof import('./src/components/layout/AppNavbar.vue')['default']
    ArrayReorderBtnGroup: typeof import('./src/components/common/ArrayReorderBtnGroup.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroupText']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    CloseButton: typeof import('./src/components/common/CloseButton.vue')['default']
    IngredientEdit: typeof import('./src/components/edit/IngredientEdit.vue')['default']
    IngredientInlineEdit: typeof import('./src/components/recipe/display/IngredientInlineEdit.vue')['default']
    IngredientModalDialogRename: typeof import('./src/components/edit/IngredientModalDialogRename.vue')['default']
    IngredientNotesFormRow: typeof import('./src/components/edit/IngredientNotesFormRow.vue')['default']
    IngredientsSection: typeof import('./src/components/recipe/display/IngredientsSection.vue')['default']
    InlineEditActionBar: typeof import('./src/components/recipe/ui/InlineEditActionBar.vue')['default']
    MetadataOverlay: typeof import('./src/components/recipe/display/MetadataOverlay.vue')['default']
    MobileIngredientsBar: typeof import('./src/components/recipe/display/MobileIngredientsBar.vue')['default']
    PortionControl: typeof import('./src/components/recipe/display/PortionControl.vue')['default']
    RecipeCard: typeof import('./src/components/recipe/ui/RecipeCard.vue')['default']
    RecipeFabMenu: typeof import('./src/components/recipe/ui/RecipeFabMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionIngredientsEdit: typeof import('./src/components/edit/SectionIngredientsEdit.vue')['default']
    StepEdit: typeof import('./src/components/edit/StepEdit.vue')['default']
    StepInlineEdit: typeof import('./src/components/recipe/display/StepInlineEdit.vue')['default']
    StepSection: typeof import('./src/components/recipe/display/StepSection.vue')['default']
  }
  export interface GlobalDirectives {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
  }
}
